### PR TITLE
Document update and fix code quality

### PR DESCRIPTION
**Pull request by kevindiu**
Please do not merge first before complete the document update.

### CODE REVIEW

**Comment by kevindiu** [comment]
It is hard for user to understand what is athenz config, so the source code and corresponding document needs to be rename.

**Comment by kpango** [comment]
Are there any ideas other than the name of athenz config?

**Comment by kevindiu** [comment]
> Are there any ideas other than the name of athenz config?

Maybe "AthenzKeyUpdater"?

**Comment by kevindiu** [comment]
Also the package name should be rename to "key"?

**Comment by kpango** [comment]
I think "PubKey" is better than "Key"

**Comment by kevindiu** [comment]
Yes! So I will rename the package name to "pubkey" and rename the interface name to "AthenzPubKeyUpdater".

**Comment by kpango** [comment]
LGTM

**Pull request merged**
